//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja_Unapec
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.Balance = 0D;
            this.MOVIMIENTOes = new HashSet<MOVIMIENTO>();
        }
        [Required]
        public int IdCliente { get; set; }
        [Required]
        public string Nombre { get; set; }

        public bool Estado { get; set; }
        [Required]
        public int IdTipoPersona { get; set; }
        [Required]
        public int IdCarrera { get; set; }
        public double Balance { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        public virtual TIPO_PERSONA TIPO_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTO> MOVIMIENTOes { get; set; }
    }
}
